/**
 * Return iterator for container
 * @param someContainer container that has iterable
 * @returns Iterable Wrapper
 */
export function iter<T>(someContainer: T[] | Set<T>) {
    return new IterWrapper<T>(someContainer[Symbol.iterator]());
}

class IterWrapper<T> {
    iterable: IterableIterator<T>;
    [Symbol.iterator](): IterableIterator<T> {
        return this.iterable;
    };
    constructor(
        iterable: IterableIterator<T>
    ) {
        this.iterable = iterable;
    }

    next(): IteratorResult<T> {
        return this.iterable.next();
    }

    /**
     * Perform operation on each value returned by iterator
     * @param fn function to perform
     */
    forEach(fn: (_: T, index?: number) => void) {
        let index = 0;
        for (const value of this) {
            fn(value, index);
            index += 1;
        }
    }

    /**
     * Return value from iterator till condition is satisfied or 
     * till the iterator ends.
     * @param fn function for validation
     */
    takeWhile(fn: (_: T, index?: number) => boolean) {
        return new IterWrapper<T>(
            function*(container) {
                let index = 0;
                for (const value of container) {
                    if (!fn(value, index)) {
                        break;
                    }
                    index += 1;
                    yield value;
                }
            }(this) as IterableIterator<T>
        );
    }

    /**
     * Maps to a different value
     * @param fn function to perform transform
     */
    map<U>(fn: (_: T, index?: number) => U): IterWrapper<U> {
        return new IterWrapper<U>(
            function*(container) {
                let index = 0;
                for (const value of container) {
                    yield fn(value, index);
                    index += 1;
                }
            }(this) as IterableIterator<U>
        );
    }

    /**
     * Check if every value generated by iterator satisfies condition
     * @param fn function for user defined check
     * @returns boolean value
     */
    every(fn: (_: T, index?: number) => boolean): boolean {
        let index = 0;
        for (const value of this) {
            if (!fn(value, index)) {
                return false
            }
            index += 1;
        }
        return true;
    }

    /**
     * Check if at least one value generated by iterator satisfies condition
     * @param fn function for user defined check
     * @returns boolean value
     */
    some(fn: (_: T, index?: number) => boolean): boolean {
        let index = 0;
        for (const value of this) {
            if (fn(value, index)) {
                return true
            }
            index += 1;
        }
        return false;
    }

    /**
     * Filter values and ignore values that does not satisfy condition
     * @param fn function to perform transform
     */
    filter(fn: (_: T, index?: number) => boolean): IterWrapper<T> {
        return new IterWrapper<T>(
            function*(container) {
                let index = 0;
                for (const value of container) {
                    if (fn(value, index)) {
                        yield value;
                    }
                    index += 1;
                }
            }(this) as IterableIterator<T>
        );
    }

    /**
     * @returns Array generated by collecting all values from iterator
     */
    collect(): Array<T> {
        return [...this.iterable];
    }
}

/**
 * Convenient iterator for nodes.
 * @param value Value to iterate towards document
 * @param strideFn the function that yields the next node based on current node
 * 
 * For e.g.,
 * ```
 * strideFn = (n: Node) => n.parentNode
 * ```
 * will jump from current to parentNode
 * 
 * @param incl Flag for inclusive, i.e., include value for which the generator does not
 * yield value further.
 * @returns wrapper for the Iterator
 */
export function nodeIter<YieldType = HTMLElement | Node>(
    value: YieldType,
    strideFn: (_: YieldType) => YieldType,
    incl: boolean = false
) {
    return new NodeIterWrapper<YieldType>(
        value,
        strideFn,
        incl,
        (par) => par !== null
    );
}

class NodeIterWrapper<YieldType> extends IterWrapper<YieldType> implements Iterable<YieldType>  {
    until: (_: YieldType) => boolean;
    constructor(
        currNode: YieldType,
        stride: (_: YieldType) => YieldType,
        inclusive: boolean = false,
        until: (_: YieldType) => boolean
    ) {
        super(
            function*() {
                while (until(currNode)) {
                    const value = currNode;
                    currNode = stride(currNode);
                    yield value;
                }
                if (inclusive) {
                    yield currNode;
                }
            }() as IterableIterator<YieldType>
        );

        this.until = until;
    }

    till(fn: (_: YieldType) => boolean) {
        this.until = fn;
        return this;
    }

    /**
     * Returns the last element returned from the iterator
     * @returns The last element from the iterator
     */
    last(): YieldType {
        let value = null;
        for (const i of this) {
            value = i;
        }
        return value;
    }
}
